title: Patrick Stünkel
description: Patrick Stünkel | Personal Homepage

url: http://webminz.github.io
baseurl: ""

remote_theme: ankitsultana/researcher@gem

markdown: kramdown

footer: yes
footer_url: "https://github.com/webminz/webminz.github.io"
footer_text: "(C) Patrick Stünkel | Jekyll theme was developed by https://github.com/ankitsultana (GNU GPL v3)"


nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"

